# SPDX-FileCopyrightText: 2026 Bora Yarkın
# SPDX-License-Identifier: GPL-3.0-only

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
      github-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      backend-python:
        applies-to: "version-updates"
        patterns:
          - "*"
      backend-python-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      frontend-dart:
        applies-to: "version-updates"
        patterns:
          - "*"
      frontend-dart-security:
        applies-to: "security-updates"
        patterns:
          - "*"
